<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="27122" started-at="2020-11-23T13:10:43 UTC" finished-at="2020-11-23T13:11:10 UTC">
    <groups>
    </groups>
    <test name="Test" duration-ms="27122" started-at="2020-11-23T13:10:43 UTC" finished-at="2020-11-23T13:11:10 UTC">
      <class name="Hackathon_Test.APITest">
        <test-method status="PASS" signature="deleteAllureReport()[pri:0, instance:Hackathon_Test.APITest@12ab8d9]" name="deleteAllureReport" is-config="true" duration-ms="103" started-at="2020-11-23T13:10:43 UTC" finished-at="2020-11-23T13:10:43 UTC">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteAllureReport -->
        <test-method status="FAIL" signature="testGoodRequest()[pri:0, instance:Hackathon_Test.APITest@12ab8d9]" name="testGoodRequest" duration-ms="27008" started-at="2020-11-23T13:10:43 UTC" description="Good Request" finished-at="2020-11-23T13:11:10 UTC">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at Hackathon_Test.APITest.printlog(APITest.java:798)
at Hackathon_Test.APITest.apiTestPASS(APITest.java:514)
at Hackathon_Test.APITest.testGoodRequest(APITest.java:281)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGoodRequest -->
        <test-method status="PASS" signature="testBadRequest()[pri:0, instance:Hackathon_Test.APITest@12ab8d9]" name="testBadRequest" duration-ms="15327" started-at="2020-11-23T13:10:43 UTC" description="Bad Request" finished-at="2020-11-23T13:10:58 UTC">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBadRequest -->
        <test-method status="PASS" signature="raiseAssertion()[pri:0, instance:Hackathon_Test.APITest@12ab8d9]" name="raiseAssertion" is-config="true" duration-ms="0" started-at="2020-11-23T13:11:10 UTC" finished-at="2020-11-23T13:11:10 UTC">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- raiseAssertion -->
        <test-method status="PASS" signature="generateAllureReport()[pri:0, instance:Hackathon_Test.APITest@12ab8d9]" name="generateAllureReport" is-config="true" duration-ms="5030" started-at="2020-11-23T13:11:10 UTC" finished-at="2020-11-23T13:11:15 UTC">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateAllureReport -->
      </class> <!-- Hackathon_Test.APITest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
